[[redirects]]
  from = "/*"
  to = "/opps"
  status = 404
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "https://doteightinc.com"
  to = "https://doteightplus.com"
  status = 301
  force = true
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"    